version: '3.8'
name: fsh-microservices

services:
  # Gateway
  gateway:
    container_name: "gateway"
    image: fsh-microservices.gateway:latest
    ports:
      - 5010:5010
      - 5100:5100
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:5100;http://+:5010
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https
    networks:
     - fsh-microservices
  
  # Identity 
  identity:
    container_name: identity
    image: fsh-microservices.identity:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https
    depends_on:
      identity-pg:
        condition: service_healthy 
    networks:
     - fsh-microservices
  identity-pg:
    container_name: "identity-pg"
    image: postgres:15-alpine
    environment:
      - POSTGRES_DATABASE=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGPORT=5210
    ports:
      - 5210:5210
    volumes:
      - identity-pg-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
     - fsh-microservices

  # Catalog
  catalog:
    container_name: catalog-service
    image: fsh-microservices.catalog:latest
    depends_on:
      - catalog-mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https
    networks:
     - fsh-microservices
  catalog-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "catalog",
     "-placement-host-address", "placement:50003"]
    depends_on:
      - catalog
    networks:
     - fsh-microservices
  catalog-mongo:
    image: mongo
    container_name: catalog-mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - catalog-mongo-data:/data/db
    networks:
      - fsh-microservices

volumes:
  identity-pg-data:
  catalog-mongo-data:

networks:
  fsh-microservices:
    name:  fsh-microservices
